### ISSUE TITLE
error: unable to find matching request for baseUrl 

### ISSUE THREAD

**Issue by aster2709** [cawfree/sameorigin#2]
hey there! i'm trying out the steps as per README. coming across an error _(inserting response data html)_

```
Error: Unable to find matching request for baseUrl "https://core-api.prod.blur.io".
    at /Users/aster27/Desktop/trade-bot/node_modules/@cawfree/sameorigin/dist/server/createServer.js:68:23
    at Layer.handle [as handle_request] (/Users/aster27/Desktop/trade-bot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/aster27/Desktop/trade-bot/node_modules/express/lib/router/index.js:328:13)
    at /Users/aster27/Desktop/trade-bot/node_modules/express/lib/router/index.js:286:9
    at param (/Users/aster27/Desktop/trade-bot/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/aster27/Desktop/trade-bot/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/Users/aster27/Desktop/trade-bot/node_modules/express/lib/router/index.js:421:3)
    at next (/Users/aster27/Desktop/trade-bot/node_modules/express/lib/router/index.js:280:10)
    at cors (/Users/aster27/Desktop/trade-bot/node_modules/cors/lib/index.js:188:7)
    at /Users/aster27/Desktop/trade-bot/node_modules/cors/lib/index.js:224:17
```

thanks!

**Comment by aster2709** [comment]
executed code
```ts
const main = async () => {
  const [axios, { close }] = await sameorigin({
    squatURL: "https://blur.io",
  })
  const { data } = await axios({
    // Important! You must declare the baseURL of the API you intend
    // to target. This is because it is used to isolate requests you
    // intend to hijack for your own purposes.
    baseURL: "https://core-api.prod.blur.io/v1",

    // GET https://core-api.prod.blur.io/v1/prices
    url: "/prices",
    method: "get",
  })
  await close()
  console.log(data)
}

main()
```

**Comment by cawfree** [comment]
Hey @aster2709! Looking through the __Network__ tab on my browser, it looks like this API request is no longer executed on the Blur homepage. If `sameorigin` cannot find the request to hijack, it won't be able to piggyback future requests on top.

I looked around a little bit and I can see that the API call has been moved to `https://blur.io/airdrop`. If you change your `squatURL` to this, the request should be detected successfully.

![image](https://user-images.githubusercontent.com/7922333/226491238-d1ab32cd-ca99-4e24-84e8-503aeb613586.png)

```typescript
const main = async () => {
  const [axios, { close }] = await sameorigin({
    squatURL: "https://blur.io/airdrop",
  })
  const { data } = await axios({
    // Important! You must declare the baseURL of the API you intend
    // to target. This is because it is used to isolate requests you
    // intend to hijack for your own purposes.
    baseURL: "https://core-api.prod.blur.io/v1",

    // GET https://core-api.prod.blur.io/v1/prices
    url: "/prices",
    method: "get",
  })
  await close()
  console.log(data)
}

main()
```

**Comment by aster2709** [comment]
hey the `/prices` did indeed work ✅ 

for the rather important routes, I'm not able to make it work 
`https://core-api.prod.blur.io/v1/collections/azuki` 
have tried various `squatUrls` for eg. `https://blur.io/collection` it sometimes works out of the blue like (1 / 10 times prolly)

im guessing these are protected routes. appreciate any info on this :v:

**Comment by cawfree** [comment]
@aster2709

I agree with your interpretation.

As far as I have experimented, you need to be signed in to query the API on other routes.

It should be possible to programmatically login to Blur using the same API functions (since, similar to `/prices`, it cannot be protected like the other routes because it must serve unauthenticated users). Very odd to hear that it sometimes randomly works, though.

I recommend manually signing into Blur and watching which API calls which get made in the Network tab; you'll need to replicate these programmatically from your script using `sameorigin` in order to access permissioned content on the Blur API.

**Comment by Philippeomalley** [comment]
Hey, did you ever manage to get this to work with the protected routes?
